/*   Do *not* directly modify this file.  It was    */
/*   generated by the Configuration Tool; any  */
/*   changes risk being overwritten.                */

/* INPUT tsk.cdb */

/*  Include Header Files  */
#include <std.h>
#include <hst.h>
#include <swi.h>
#include <tsk.h>
#include <log.h>
#include <sem.h>
#include <sts.h>

#ifdef __cplusplus
extern "C" {
#endif

extern HST_Obj RTA_fromHost;
extern HST_Obj RTA_toHost;
extern SWI_Obj KNL_swi;
extern TSK_Obj TSK_idle;
extern TSK_Obj TSK_AudioProcessing;
extern TSK_Obj TSK_OutputAudio;
extern TSK_Obj TSK_FFTProcessor;
extern LOG_Obj LOG_system;
extern LOG_Obj trace;
extern SEM_Obj SEM_AudioProcessor;
extern SEM_Obj SEM_OutputAudio;
extern SEM_Obj SEM_FFTProcessor;
extern SEM_Obj SEM_StartUI;
extern STS_Obj IDL_busyObj;


#ifdef __cplusplus
}
#endif /* extern "C" */
